import {useEffect,useMemo,useState} from 'react'
import {BrowserRouter,Navigate,NavLink,Route,Routes,useNavigate} from 'react-router-dom'
import {AlertTriangle,BarChart3,Bell,Building2,CheckCircle2,ChevronRight,CircleDollarSign,Clock3,FileText,Home,LogOut,Menu,Plus,Search,ShieldCheck,Ticket,Wrench,X} from 'lucide-react'
import {AuthProvider,useAuth} from './context/AuthContext'
import {api} from './lib/api'
import './App.css'

const fmtMoney=(value)=>new Intl.NumberFormat('es-PY',{style:'currency',currency:'PYG',maximumFractionDigits:0}).format(value||0)
const label=(value)=>String(value||'').replaceAll('_',' ').replace(/^./,(x)=>x.toUpperCase())
const demoAccounts=[['Administrador','admin@gestionincidencias.test'],['Vecino','vecino@gestionincidencias.test'],['Proveedor','proveedor@gestionincidencias.test'],['Superadmin','super@gestionincidencias.test']]

function Login(){const {login,user}=useAuth();const nav=useNavigate();const [email,setEmail]=useState('admin@gestionincidencias.test');const [password,setPassword]=useState('Demo2026!');const [error,setError]=useState('');const [loading,setLoading]=useState(false);if(user)return <Navigate to="/" replace/>;const submit=async(e)=>{e.preventDefault();setLoading(true);setError('');try{await login(email,password);nav('/')}catch(err){setError(err.response?.data?.message||'No fue posible conectar con la API.')}finally{setLoading(false)}};return <main className="login-shell"><section className="login-story"><div className="brand brand-light"><span className="brand-mark"><Ticket/></span><span>Gestión de <b>Incidencias</b></span></div><div className="story-copy"><span className="eyebrow">Comunidades mejor conectadas</span><h1>Resolver juntos empieza por reportar mejor.</h1><p>Incidencias claras, responsables visibles y seguimiento sin perseguir mensajes en grupos.</p><div className="story-stats"><div><strong>24/7</strong><span>trazabilidad</span></div><div><strong>1 lugar</strong><span>para toda la comunidad</span></div></div></div><div className="story-art" aria-hidden="true"><div className="building"><i/><i/><i/><i/><i/><i/></div><div className="tree">♣</div></div></section><section className="login-panel"><form className="login-card" onSubmit={submit}><div className="mobile-brand brand"><span className="brand-mark"><Ticket/></span><span>Gestión de <b>Incidencias</b></span></div><span className="eyebrow green">Acceso seguro</span><h2>Bienvenido de nuevo</h2><p className="muted">Ingresá con tu cuenta para continuar.</p><label>Correo electrónico<input value={email} onChange={(e)=>setEmail(e.target.value)} type="email" autoComplete="email" required/></label><label>Contraseña<input value={password} onChange={(e)=>setPassword(e.target.value)} type="password" autoComplete="current-password" required/></label>{error&&<div className="alert"><AlertTriangle size={18}/>{error}</div>}<button className="primary wide" disabled={loading}>{loading?'Ingresando…':'Ingresar'}<ChevronRight size={18}/></button><div className="demo-box"><strong>Perfiles de demostración</strong><p>Contraseña para todos: <code>Demo2026!</code></p><div className="demo-grid">{demoAccounts.map(([name,mail])=><button type="button" key={mail} onClick={()=>setEmail(mail)}>{name}</button>)}</div></div></form></section></main>}

const navByRole={superadministrador:[['/','Resumen',BarChart3],['/comunidades','Comunidades',Building2],['/planes','Planes SaaS',FileText],['/incidencias','Incidencias',Ticket],['/proveedores','Proveedores',Wrench],['/pagos','Pagos',CircleDollarSign]],administrador:[['/','Resumen',BarChart3],['/incidencias','Incidencias',Ticket],['/proveedores','Proveedores',Wrench],['/pagos','Pagos',CircleDollarSign],['/reportes','Informes',FileText]],vecino:[['/','Mi inicio',Home],['/incidencias','Incidencias',Ticket],['/incidencias/nueva','Reportar',Plus],['/pagos','Mis pagos',CircleDollarSign]],proveedor:[['/','Mi trabajo',Home],['/incidencias','Asignaciones',Wrench],['/pagos','Cobros',CircleDollarSign]]}
function Layout({children}){const {user,logout}=useAuth();const [open,setOpen]=useState(false);const role=user?.role?.nombre||'vecino';const items=navByRole[role]||navByRole.vecino;return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><span className="brand-mark"><Ticket/></span><span>Gestión de <b>Incidencias</b></span><button className="icon-button sidebar-close" onClick={()=>setOpen(false)} aria-label="Cerrar menú"><X/></button></div><nav>{items.map(([to,text,Icon])=><NavLink end={to==='/'} key={to} to={to} onClick={()=>setOpen(false)}><Icon size={20}/><span>{text}</span></NavLink>)}</nav><div className="support-card"><ShieldCheck/><strong>Datos protegidos</strong><span>Acceso seguro y acciones auditadas.</span></div><button className="logout" onClick={logout}><LogOut size={19}/>Cerrar sesión</button></aside><main className="main"><header className="topbar"><button className="icon-button menu-button" onClick={()=>setOpen(true)} aria-label="Abrir menú"><Menu/></button><div><span className="community">{user?.comunidad?.nombre||'Administración global'}</span><small>Asunción, Paraguay</small></div><div className="top-actions"><button className="icon-button" aria-label="Notificaciones"><Bell/></button><div className="avatar">{user?.nombre?.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div className="user-meta"><strong>{user?.nombre}</strong><span>{label(role)}</span></div></div></header><div className="content">{children}</div></main>{open&&<button className="backdrop" onClick={()=>setOpen(false)} aria-label="Cerrar menú"/>}</div>}
function Protected({children}){const {user}=useAuth();return user?<Layout>{children}</Layout>:<Navigate to="/login" replace/>}
function PageHeader({eyebrow,title,description,action}){return <div className="page-header"><div><span className="eyebrow green">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>}
function Stat({icon:Icon,labelText,value,detail,tone='green'}){return <article className="stat"><span className={`stat-icon ${tone}`}><Icon/></span><div><span>{labelText}</span><strong>{value}</strong><small>{detail}</small></div></article>}
function Empty({text}){return <div className="empty"><CheckCircle2/><p>{text}</p></div>}
function Dashboard(){const {user}=useAuth();const [data,setData]=useState(null);const [incidents,setIncidents]=useState([]);useEffect(()=>{Promise.all([api.get('/dashboard'),api.get('/incidencias')]).then(([d,i])=>{setData(d.data);setIncidents(i.data.data.slice(0,5))})},[]);const role=user.role.nombre;return <><PageHeader eyebrow="Panel principal" title={`Hola, ${user.nombre.split(' ')[0]}`} description={role==='vecino'?'Este es el estado de tu comunidad hoy.':'Todo lo importante de la gestión, en una sola vista.'} action={role==='vecino'?<NavLink to="/incidencias/nueva" className="primary"><Plus size={18}/>Reportar incidencia</NavLink>:null}/><section className="stats-grid"><Stat icon={Ticket} labelText="Incidencias" value={data?.total??'—'} detail={`${data?.abiertas??0} requieren atención`}/><Stat icon={CheckCircle2} labelText="Resueltas" value={data?.resueltas??'—'} detail="Histórico registrado" tone="blue"/><Stat icon={Clock3} labelText="Tiempo promedio" value={`${data?.tiempo_promedio_horas??0} h`} detail="Hasta la resolución" tone="amber"/><Stat icon={CircleDollarSign} labelText="Pagos confirmados" value={fmtMoney(data?.monto_pagado)} detail={`${fmtMoney(data?.monto_pendiente)} pendientes`} tone="purple"/></section><section className="dashboard-grid"><article className="panel span-2"><div className="panel-head"><div><h2>Actividad reciente</h2><p>Últimas incidencias de la comunidad</p></div><NavLink to="/incidencias">Ver todas <ChevronRight size={16}/></NavLink></div><IncidentTable items={incidents}/></article><article className="panel"><div className="panel-head"><div><h2>Estado general</h2><p>Distribución actual</p></div></div><div className="status-list">{data?.por_estado?.map((x,i)=><div key={x.estado_actual}><span><i className={`dot d${i}`}/>{label(x.estado_actual)}</span><strong>{x.total}</strong><div className="bar"><i style={{width:`${Math.max(8,x.total/(data.total||1)*100)}%`}}/></div></div>)}</div></article></section></>}
function StatusBadge({value}){return <span className={`badge ${value}`}>{label(value)}</span>}
function IncidentTable({items}){if(!items.length)return <Empty text="No hay incidencias para mostrar."/>;return <div className="table-wrap"><table><thead><tr><th>Incidencia</th><th>Prioridad</th><th>Estado</th><th>Proveedor</th><th>Fecha</th></tr></thead><tbody>{items.map(x=><tr key={x.id_incidencia}><td><strong>#{String(x.id_incidencia).padStart(4,'0')} · {x.titulo}</strong><span>{x.descripcion}</span></td><td><span className={`priority ${x.prioridad}`}>{label(x.prioridad)}</span></td><td><StatusBadge value={x.estado_actual}/></td><td>{x.proveedor?.nombre_completo||'Sin asignar'}</td><td>{new Date(x.fecha_creacion).toLocaleDateString('es-PY')}</td></tr>)}</tbody></table></div>}
function Incidents(){const [items,setItems]=useState([]);const [query,setQuery]=useState('');const [state,setState]=useState('');useEffect(()=>{api.get('/incidencias',{params:{estado_actual:state||undefined}}).then(r=>setItems(r.data.data))},[state]);const filtered=useMemo(()=>items.filter(x=>`${x.titulo} ${x.descripcion}`.toLowerCase().includes(query.toLowerCase())),[items,query]);return <><PageHeader eyebrow="Gestión operativa" title="Incidencias" description="Consultá, filtrá y seguí cada solicitud de la comunidad." action={<NavLink to="/incidencias/nueva" className="primary"><Plus size={18}/>Nueva incidencia</NavLink>}/><article className="panel"><div className="filters"><label className="search"><Search/><input placeholder="Buscar por título o descripción" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={state} onChange={e=>setState(e.target.value)}><option value="">Todos los estados</option><option value="pendiente">Pendiente</option><option value="asignado">Asignado</option><option value="en_proceso">En proceso</option><option value="resuelto">Resuelto</option></select></div><IncidentTable items={filtered}/></article></>}
function NewIncident(){const nav=useNavigate();const [form,setForm]=useState({titulo:'',descripcion:'',prioridad:'media'});const [error,setError]=useState('');const [saving,setSaving]=useState(false);const submit=async(e)=>{e.preventDefault();setSaving(true);try{await api.post('/incidencias',form);nav('/incidencias')}catch(err){setError(err.response?.data?.message||'No se pudo registrar.')}finally{setSaving(false)}};return <><PageHeader eyebrow="Nuevo reporte" title="Contanos qué ocurrió" description="Describí el problema con claridad para que podamos atenderlo más rápido."/><article className="panel form-panel"><form onSubmit={submit}><div className="form-section"><span className="step">1</span><div><h2>Detalles de la incidencia</h2><p>Usá un título breve y una descripción precisa.</p></div></div><label>Título<input value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} placeholder="Ej.: Fuga de agua en el pasillo" required maxLength={160}/></label><label>Descripción<textarea value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})} placeholder="Indicá dónde ocurre, desde cuándo y cualquier detalle útil…" required rows={6}/></label><fieldset><legend>Prioridad</legend><div className="priority-options">{['baja','media','alta','urgente'].map(p=><label key={p} className={form.prioridad===p?'selected':''}><input type="radio" name="priority" value={p} checked={form.prioridad===p} onChange={()=>setForm({...form,prioridad:p})}/><strong>{label(p)}</strong><span>{p==='urgente'?'Riesgo o servicio crítico':p==='alta'?'Atención prioritaria':p==='media'?'Afecta el uso habitual':'Puede programarse'}</span></label>)}</div></fieldset>{error&&<div className="alert">{error}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={()=>nav(-1)}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Registrando…':'Registrar incidencia'}<ChevronRight size={18}/></button></div></form></article></>}
function Payments(){const [items,setItems]=useState([]);useEffect(()=>{api.get('/pagos').then(r=>setItems(r.data))},[]);return <><PageHeader eyebrow="AdamsPay" title="Pagos y presupuestos" description="Consultá las deudas y el estado de cada operación en guaraníes."/><section className="payment-grid">{items.map(x=><article className="payment-card" key={x.id_pago}><div><StatusBadge value={x.estado_pago}/><span>Documento {x.doc_id}</span></div><h2>{fmtMoney(x.monto)}</h2><p>{x.incidencia?.titulo||'Orden de pago de la comunidad'}</p>{x.estado_pago==='pendiente'?<a className="primary" href={x.url_pago_adams}>Pagar con AdamsPay <ChevronRight size={17}/></a>:<span className="paid"><CheckCircle2/>Pago confirmado</span>}</article>)}</section>{!items.length&&<article className="panel"><Empty text="No tenés pagos registrados."/></article>}</>}
function Providers(){const [items,setItems]=useState([]);useEffect(()=>{api.get('/proveedores').then(r=>setItems(r.data.data))},[]);return <><PageHeader eyebrow="Red de servicios" title="Proveedores" description="Especialistas registrados para atender a la comunidad."/><section className="provider-grid">{items.map(x=><article className="provider-card" key={x.id_proveedor}><span className="provider-icon"><Wrench/></span><div><h2>{x.nombre_completo}</h2><p>{x.especialidad}</p><span>★ {x.calificacion_promedio} · {x.incidencias_count} trabajos</span></div><button className="secondary">Ver perfil</button></article>)}</section></>}
function Placeholder({type}){return <><PageHeader eyebrow="Administración" title={type} description="Módulo preparado para la gestión integral de la plataforma."/><article className="panel"><Empty text={`${type}: sin registros adicionales en la demo inicial.`}/></article></>}
function AppRoutes(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/" element={<Protected><Dashboard/></Protected>}/><Route path="/incidencias" element={<Protected><Incidents/></Protected>}/><Route path="/incidencias/nueva" element={<Protected><NewIncident/></Protected>}/><Route path="/pagos" element={<Protected><Payments/></Protected>}/><Route path="/proveedores" element={<Protected><Providers/></Protected>}/><Route path="/comunidades" element={<Protected><Placeholder type="Comunidades"/></Protected>}/><Route path="/planes" element={<Protected><Placeholder type="Planes SaaS"/></Protected>}/><Route path="/reportes" element={<Protected><Placeholder type="Informes mensuales"/></Protected>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}
export default function App(){return <BrowserRouter><AuthProvider><AppRoutes/></AuthProvider></BrowserRouter>}
